[theme]
#define a cor primária
primaryColor="#fddbdf"

#define a cor de fundo
backgroundColor="#fffffe"

#define a cor de fundo secundária
secondaryBackgroundColor="#f1f2f6"

#define a cor do texto
textColor="#31333e"
