[theme]
#define a cor primária
primaryColor="#ffffff"

#define a cor de fundo
backgroundColor="#f6e8ff"

#define a cor de fundo secundária
secondaryBackgroundColor="#6c4e80"

#define a cor do texto
textColor="#000000"

#define a fonte do texto
font="serif"
